// 系统错误类型（用于日志记录）
export enum SystemErrorType {
	// 系统错误
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	DATABASE_ERROR = 'DATABASE_ERROR',
	NETWORK_ERROR = 'NETWORK_ERROR',
	API_ERROR = 'API_ERROR',
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	// 认证错误
	AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
	AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
	TOKEN_EXPIRED = 'TOKEN_EXPIRED',
	// 资源错误
	RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
	RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
	RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'
}

// 用户错误类型（前端显示）
export enum UserErrorType {
	// 钱包错误
	WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
	WALLET_CONNECTION_FAILED = 'WALLET_CONNECTION_FAILED',
	WALLET_CHAIN_NOT_SUPPORTED = 'WALLET_CHAIN_NOT_SUPPORTED',
	WALLET_BALANCE_INSUFFICIENT = 'WALLET_BALANCE_INSUFFICIENT',

	// 交易错误
	TRANSACTION_FAILED = 'TRANSACTION_FAILED',
	TRANSACTION_REJECTED = 'TRANSACTION_REJECTED',
	TRANSACTION_TIMEOUT = 'TRANSACTION_TIMEOUT',

	// 输入错误
	INVALID_INPUT = 'INVALID_INPUT',
	INVALID_ADDRESS = 'INVALID_ADDRESS',
	INVALID_AMOUNT = 'INVALID_AMOUNT'
}
